name: Publish OpenAPI Specification
run-name: 🫸 Publish openapi.yml for "${{ github.event.head_commit.message || github.sha }}"

on:
  push:
    branches:
      - main
    paths:
        - "openapi/openapi.yml"
  workflow_dispatch:

jobs:
  validate-schema:
    name: Validate OpenAPI Schema
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
        with:
          sparse-checkout: 'openapi'
          sparse-checkout-cone-mode: true

      - name: Fetch Main
        run: git fetch origin main --depth=1

      - name: Read Main OpenAPI version
        id: main_spec
        run: |
          MAIN_VERSION=$(git show origin/main:openapi/openapi.yml | yq '.info.version')
          echo "version=$MAIN_VERSION" >> "$GITHUB_OUTPUT"

      - name: Read Feature Branch OpenAPI version
        id: feature_spec
        working-directory: .
        run: |
          FEATURE_VERSION=$(yq '.info.version' openapi/openapi.yml)
          echo "version=$FEATURE_VERSION" >> "$GITHUB_OUTPUT"

      - name: Gate - Fail if Main and Feature Branch OpenAPI Version differ
        if: github.ref_name != 'main'
        env:
          MAIN_VER: ${{ steps.main_spec.outputs.version }}
          FEATURE_VER: ${{ steps.feature_spec.outputs.version }}
        run: |
          if [ "$MAIN_VER" != "$FEATURE_VER" ]; then
            echo "::error::openapi.yml version ($FEATURE_VER) doesn't match main ($MAIN_VER). Please rebase/merge main branch onto this feature branch to continue..."
            exit 1
          fi

  version-bump:
    name: Determine OpenAPI Version
    needs: validate-schema
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7
        with:
          fetch-depth: 0 # Needed to repush

      - name: Bump or tag version
        id: set_version
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
          GITHUB_WORKFLOW_SHA: ${{ github.workflow_sha }}
        run: |
          OLD_VERSION=$(yq '.info.version' openapi/openapi.yml)

          if [ "$GITHUB_REF_NAME" == "main" ]; then
            MAJOR=$(echo $OLD_VERSION | cut -d. -f1)
            MINOR=$(echo $OLD_VERSION | cut -d. -f2)
            PATCH=$(echo $OLD_VERSION | cut -d. -f3)
            NEW_VERSION="${MAJOR}.${MINOR}.$((PATCH + 1))"
            yq -i ".info.version = \"$NEW_VERSION\"" openapi/openapi.yml

            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add openapi/openapi.yml
            git commit -m "chore: bump openapi version to ${NEW_VERSION} [skip ci]"
            git push
          else
            SANITIZED_BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/[^a-zA-Z0-9]/-/g')
            NEW_VERSION="${OLD_VERSION}-feature-branch-${SANITIZED_BRANCH_NAME}-${GITHUB_WORKFLOW_SHA}"
          fi

          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Upload updated openapi.yml
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: updated-openapi-spec
          path: openapi/openapi.yml

  build-and-publish:
    name: Build and Publish Generated OpenAPI
    needs: version-bump
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NEW_VERSION: ${{ needs.version-bump.outputs.version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7

      - name: Download updated openapi.yml
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v4.0.1
        with:
          name: updated-openapi-spec
          path: openapi

      - name: Setup bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 #v2.2.0
        with:
          bun-version: 1.3.14

      - name: Install dependencies
        working-directory: ./openapi
        run: |
          bun install --frozen-lockfile

      - name: Assign new version, generate, and build
        working-directory: ./openapi
        run: |
          set -euo pipefail
          bun pm version ${NEW_VERSION} --no-git-tag-version
          bunx @hey-api/openapi-ts@next -f openapi-ts.config.ts
          bun run build

      - name: Publish
        working-directory: ./openapi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [ ${GITHUB_REF_NAME} == 'main' ]; then
            bun publish
          else
            bun publish --tag ${NEW_VERSION}
          fi
